# HTTP config
token: 1913597879:AAEQ8hYhCyNoavFzxHWYcf2Lg-ejOSt48NU
timeout: 5

# Logger config
mode: Both
priority: Info
file: log.txt

# Bot config
repeatQuestion: Current repeat value
help: You're my frien now :>
defaultRepeat: 1
