# HTTP config
token: 1913597879:AAEQ8hYhCyNoavFzxHWYcf2Lg-ejOSt48NU
timeout: 40

# Logger config
mode: File
priority: Error
file: log.txt

# Bot config
question: Current repeat value
help: You're my frien now :>
repeat: 1
