# HTTP config
token: 1913597879:AAEQ8hYhCyNoavFzxHWYcf2Lg-ejOSt48NU
timeout: 20

# Logger config
mode: Stdout
priority: Info
file: log.txt

# Bot config
question: Current repeat value
help: I'm the echo bot.
repeat: 1
