token: 1913597879:AAEQ8hYhCyNoavFzxHWYcf2Lg-ejOSt48NU
timeout: 5
repeat: 2
debug_JSONLogFile: updates.json
logFile: log.txt
repeatQuestion: Current repeat value 
help: You're my frien now :>
logMode: ALL
messager: tg # tg or vk
